version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-proxy/external-host.d:/etc/nginx/external-host.d:ro
  dlsite-server:
    image: nginx:alpine
    container_name: dlsite-server
    restart: always
    volumes:
      - ../mini-player/:/usr/share/nginx/html:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=${SERVER_NAME}
  file-server:
    image: nginx:alpine
    container_name: file-server
    restart: always
    volumes:
      - /srv/dev-disk-by-uuid-cafe34d9-5221-4f8e-a3cc-cd3d41cf11b1/private/mp3/:/usr/share/nginx/html/mp3:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d
  api-server:
    build: golang
    container_name: api-server
    tty: true
    restart: always
    volumes:
      - ../api/:/app
      - /srv/dev-disk-by-uuid-cafe34d9-5221-4f8e-a3cc-cd3d41cf11b1/private/mp3/:/mp3:ro

