version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      # - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
  dlsite-server:
    image: nginx:alpine
    container_name: dlsite-server
      # restart: always
    volumes:
      - ../mini-player/:/usr/share/nginx/html:ro
    # ports:
    #   - 3000:80
    environment:
      - VIRTUAL_HOST=${SERVER_NAME}
  api-server:
    build: golang
    container_name: api-server
    # tty: true
    ports:
      - 8080:80
    volumes:
      - ../api/:/app
    # environment:
    #   - VIRTUAL_HOST=api.dotenn.com
