settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: app
  path: .
  commands: 
    run:
      status: true
      method: /go/bin/api
    build:
      status: true
      method: go build -o /go/bin/api
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
